### ISSUE TITLE
Tweaks Roothide

### ISSUE THREAD

**Issue by TweaksDev22** [TweaksDev22/Tweakslist#1]
**if you test any tweaks and working prefect in roothide jailbreak , i hope you share it here so we can update the list tweak :D**

**Comment by Faex-an** [comment]
I use, smoothcursor and deletecut which works without any issue.

**Comment by TweaksDev22** [comment]
@Faex-an Thank i will update list  😘

**Comment by Faex-an** [comment]
I have more tweaks: deletecut breaks preferences but works in the keyboard only. 

- Settingsrevamped
- Anykeytrackpad
- Pancake

**Comment by TweaksDev22** [comment]
@Faex-an  ty for testing tweaks will add tweaks  only working  prefect but other tweaks  make crash or broken preferences  will not adding  it

**Comment by Invisible40** [comment]
Hi, have you been able to get DeleteCut to work?
